engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 20
        javascript:
          mass_threshold: 50
  flog:
    enabled: true
  brakeman:
    enabled: true
  markdownlint:
    enabled: true
  bundler-audit:
    enabled: true
      
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
  - spec/**/*
  - "**/vendor/**/*"
  - config/environments/*.rb
  - lib/tasks/*.rake
  - db/seeds.rb
  - db/migrate/*.rb
