sudo: false
language: ruby
cache: bundler
rvm:
- 2.4
services:
- postgresql
- elasticsearch
- redis-server
before_script:
- sleep 10
script:
- bundle exec rails db:create
- bundle exec rails db:schema:load
- bundle exec rails spec
- bundle exec codeclimate-test-reporter
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - RAILS_ENV=test
after_success:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install cf-cli
deploy:
  - provider: script
    script: scripts/deploy.sh publish-data-beta-staging staging-app
    on:
      branch: master
  - provider: script
    script: scripts/deploy.sh publish-data-beta-staging-worker staging-worker
    on:
      branch: master
  - provider: script
    script: scripts/deploy.sh publish-data-beta production-app
    on:
      branch: production
  - provider: script
    script: scripts/deploy.sh publish-data-beta-worker production-worker
    on:
      branch: production
