version: '3'
services:
  web:
    build: .
    environment:
      - REDIS_IP=redis
      - ES_HOST=elasticsearch
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - sidekiq
      - elasticsearch

  db:
    image: 'postgres:9.6-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/usr/src/app'
    env_file:
      - '.env'
    depends_on:
      - 'db'
      - 'redis'

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.2.2'
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  redis:
  postgres:
  elasticsearch:
    driver: local
