applications:
- name: publish-beta-production-worker
  memory: 1G
  buildpack: https://github.com/cloudfoundry/ruby-buildpack.git#v1.9.3
  stack: cflinuxfs3
  command: bundle exec rake db:migrate db:seed && bundle exec sidekiq
  env:
    RAILS_ENV: production
    RACK_ENV: production
  services:
  - publish-production-secrets
  - publish-beta-production-pg-12
  - publish-beta-production-redis
  - logit-ssl-drain
  - opensearch-production
  health-check-type: process
