default: &default
  timeout: 5

test:
  <<: *default
  host: 'http://localhost:9200'

development:
  <<: *default
  host: 'http://localhost:9200'

integration:
  <<: *default
  host: '<%= ENV["BONSAI_URL"] %>'

staging:
  <<: *default
  host: '<%= JSON.parse(ENV["VCAP_SERVICES"] || "{}")
                 .dig("elasticsearch", 0, "credentials", "uri") %>'

production:
  <<: *default
  host: '<%= JSON.parse(ENV["VCAP_SERVICES"] || "{}")
                 .dig("elasticsearch", 0, "credentials", "uri") %>'
